[ 2023-10-05 16:00:59,490 ] 96 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.123:5000
[ 2023-10-05 16:00:59,490 ] 96 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2023-10-05 16:01:04,543 ] 825 app - ERROR - Exception on /predictdata [GET]
Traceback (most recent call last):
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 21, in predict_datapoint
    return render_template('templates/home.html')
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: templates/home.html
[ 2023-10-05 16:01:04,550 ] 96 werkzeug - INFO - 127.0.0.1 - - [05/Oct/2023 16:01:04] "[35m[1mGET /predictdata HTTP/1.1[0m" 500 -
[ 2023-10-05 16:01:05,926 ] 825 app - ERROR - Exception on /predictdata [GET]
Traceback (most recent call last):
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 21, in predict_datapoint
    return render_template('templates/home.html')
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/faraymajid/mlops_project/venv/lib/python3.8/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: templates/home.html
[ 2023-10-05 16:01:05,927 ] 96 werkzeug - INFO - 127.0.0.1 - - [05/Oct/2023 16:01:05] "[35m[1mGET /predictdata HTTP/1.1[0m" 500 -
